### ISSUE TITLE
labeling inconsistency with nDPI

### ISSUE THREAD

**Issue by RadionBik** [aouinizied/nfstream#1]
Hello!

I checked how your lib labels flows in comparison with nDPI and found out that sometimes there are mismatches.

The nDPI's  (for v.2.x and the latest dev) and your lib's outputs for a single pcap are enclosed.
[2x_ndpi_out.txt](https://github.com/aouinizied/nfstream/files/3747885/2x_ndpi_out.txt)
[latest_ndpi_output.txt](https://github.com/aouinizied/nfstream/files/3747886/latest_ndpi_output.txt)
[nfstream_output.txt](https://github.com/aouinizied/nfstream/files/3747887/nfstream_output.txt)

Also, is it possible to include the flow category (network, system, etc.) to the output as well? Adding the following snippet to `exporter` method didn't resulted in smth meaningful:

```
category_name = cast(ndpi.ndpi_get_proto_name(self.__inspector, flow.detected_protocol.category), c_char_p).value.decode('utf-8')

flow.application_name = master_name + '.' + app_name  + '.' + category_name`
```

**Comment by aouinizied** [comment]
Hi RadionBik,

Thank you for the report. It's not 'my lib' bur 'our lib' as you contribute to it too.
Please note that tests repository is constructed based on nDPI output.
nDPI as lib have two level for app idententification: master and app_protocol
In the output you generated nDPIReader remove maste if it's unknown for printing convenience.
So when you find that nfstream reports Unknown.Facebook whereas nDPI Reader output Facebook.
So I consider that there we must report both in nfstream output. User can format the output as he wants.

Regarding the category, it will be added in next release. However it will be be a new field in nfstream flow output. 
flow.category_name

**Comment by RadionBik** [comment]
Thank you for the fast reply.

Okay, I understand that the ndpiReader truncates the class name, but have a look at the class distribution generated by our lib (the bottom part of the file), for example, the detection numbers  for HTTP and  Unknown categories are different.

**Comment by aouinizied** [comment]
Another time, it's do for printing convenience. When ndpiReader reports these statistics, it simply dumps cumulative hits counter per app_name. (line 1325 in ndpiReader.c) 

```c
ndpi_thread_info[thread_id].workflow->stats.protocol_flows[flow->detected_protocol.app_protocol]++;
```

 In your provided example, just have a look at Microsoft case (number of flows):
* nfstream output you will have two entries: TLS.Microsoft (2), DNS.Microsoft (1)
* ndpi_ourput: Microsoft (3)

So there is no consistency.

**Comment by aouinizied** [comment]
category added in https://github.com/aouinizied/nfstream/commit/9398348d3b425e4dc7075ccb6eb702651ab663a0
