### ISSUE TITLE
Timestamp data is changed

### ISSUE THREAD

**Issue by tanjoreg** [aouinizied/nfstream#10]
I converted the instagram.pcap to pandas. I observed that the "first_seen", "last_seen" **dates for the first row are SAME** and **rest of the rows are in a different format** (not Unix time). I checked this is behaving correctly in your tutorial.

The following is from my jupyter:
df2 = NFStreamer(source="instagram.pcap").to_pandas()
df2

id | first_seen | last_seen | version | src_port | dst_port | protocol | vlan_id | src_ip | dst_ip | ... | dst2src_bytes | expiration_id | master_protocol | app_protocol | application_name | category_name | client_info | server_info | j3a_client | j3a_server
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | **1436720898354** | **1436720898354** | 4 | 56382 | 443 | 6 | 4 | 192.168.0.103 | 173.252.107.4 | ... | 0 | 1 | 91 | 119 | TLS.Facebook | SocialNetwork |   |   |   |  
27 | **8214173356437249** | **8214173356438953** | 4 | 80 | 58216 | 6 | 4 | 31.13.86.52 | 192.168.0.103 | ... | 3102 | 0 | 7 | 119 | HTTP.Facebook | SocialNetwork |   |   |   |  
19 | **8214173356394873** | **8214173356394919** | 4 | 26540 | 53 | 17 | 4 | 192.168.0.103 | 8.8.8.8 | ... | 209 | 0 | 5 | 211 | DNS.Instagram | SocialNetwork |   | igcdn-photos-g-a.akamaihd.net |   |  
6 | **8214173356387521** | **8214173356394883** | 4 | 33976 | 80 | 6 | 4 | 192.168.0.103 | 77.67.29.17 | ... | 28115 | 0 | 0 | 7 | HTTP | Web |   |   |   |  
23 | **8214173356394921** | **8214173356395109** | 4 | 60908 | 443 | 6 | 4 | 192.168.0.103 | 46.33.70.136 | ... | 7971 | 0 | 91 | 211 | TLS.Instagram | SocialNetwork | igcdn-photos-g-a.akamaihd.net | a248.e.akamai.net,*.akamaihd.net,*.akamaihd-st... | 54ae5fcb0159e2ddf6a50e149221c7c7 | 34d6f0ad0a79e4cfdf1

The following is from your tutorial (https://github.com/aouinizied/nfstream-tutorials/blob/master/demo_notebook.ipynb). Here everything is correct.

id | first_seen | last_seen | version | src_port | dst_port | protocol | vlan_id | src_ip | dst_ip | ... | dst2src_bytes | expiration_id | master_protocol | app_protocol | application_name | category_name | client_info | server_info | j3a_client | j3a_server
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
27 | 1436720950909 | 1436720952614 | 4 | 80 | 58216 | 6 | 4 | 31.13.86.52 | 192.168.0.103 | 150 | 153558 | 1705 | 103 | 150456 | 47 | 3102 | 0 | 7 | 119 | HTTP.Facebook | SocialNetwork |   |   |   |  
19 | 1436720908533 | 1436720908579 | 4 | 26540 | 53 | 17 | 4 | 192.168.0.103 | 8.8.8.8 | 2 | 298 | 46 | 1 | 89 | 1 | 209 | 0 | 5 | 211 | DNS.Instagram | SocialNetwork |   | igcdn-photos-g-a.akamaihd.net |   |  
6 | 1436720901182 | 1436720908544 | 4 | 33976 | 80 | 6 | 4 | 192.168.0.103 | 77.67.29.17 | 34 | 29039 | 7362 | 14 | 924 | 20 | 28115 | 0 | 0 | 7 | HTTP | Web |   |   |   |  
23 | 1436720908581 | 1436720908769 | 4 | 60908 | 443 | 6 | 4 | 192.168.0.103 | 46.33.70.136 | 19 | 9340 | 188 | 10 | 1369 | 9 | 7971 | 0 | 91 | 211 | TLS.Instagram | SocialNetwork | igcdn-photos-g-a.akamaihd.net | a248.e.akamai.net,*.akamaihd.net,*.akamaihd-st... | 54ae5fcb0159e2ddf6a50e149221c7c7 | 34d6f0ad0a79e4cfdf145e640cc93f78
29 | 1436720952561 | 1436720952561 | 4 | 58690 | 443 | 6 | 4 | 192.168.0.103 | 46.33.70.159 | 2

Am I missing something? 

System Details:
macOS Mojave 10.14.5
nfstream 3.2.2

**Comment by aouinizied** [comment]
I cannot reproduce as I do not have macOS Majave.
nfstream is tested on ubuntu and macos 10.15.

What you reported looks more like a libpcap mis-alignement in structure.
Could you provide us with your pcap.h installed on your machine?

**Comment by tanjoreg** [comment]
> I cannot reproduce as I do not have macOS Majave.
> nfstream is tested on ubuntu and macos 10.15.
> 
> What you reported looks more like a libpcap mis-alignement in structure.
> Could you provide us with your pcap.h installed on your machine?
I am upgrading my macOS which will take time.
And I am sorry I am new to this network stuff. can you help me locate that file? In which directory can I find it?

**Comment by tanjoreg** [comment]
I have upgraded macOS to latest 10.15 (catalina). and tried the following command. Still 3.1.2 is being installed.

MEs-MacBook-Pro:Assignments$ pip install --no-cache-dir --upgrade nfstream
Collecting nfstream
  Downloading https://files.pythonhosted.org/packages/9c/ca/7ae7e66e26e2827baa4c045e8a849b089ddc1735209e3d49c61fe541ec98/nfstream-3.1.2-cp36-cp36m-macosx_10_13_x86_64.whl (320kB)
     |████████████████████████████████| 327kB 688kB/s 
Requirement already satisfied, skipping upgrade: pyzmq>=18.1.1 in /Users/ME/anaconda3/lib/python3.6/site-packages (from nfstream) (19.0.0)
Requirement already satisfied, skipping upgrade: cffi>=1.13.1 in /Users/ME/anaconda3/lib/python3.6/site-packages (from nfstream) (1.14.0)
Requirement already satisfied, skipping upgrade: pycparser in /Users/ME/anaconda3/lib/python3.6/site-packages (from cffi>=1.13.1->nfstream) (2.18)
Installing collected packages: nfstream
Successfully installed nfstream-3.1.2
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by aouinizied** [comment]
try with python3.7 which is the default version on macOS catalina and it must work.

**Comment by tanjoreg** [comment]
You are right...this has something to do with latest macOS and this issue is not relevant in 10.15. when I install 'nfstream' via git clone. I will close this issue.

**Comment by aouinizied** [comment]
https://pypi.org/project/nfstream/#files

As you can see, we currently publish only one wheel for macOS Catalina on its default python version which is 3.7

**Comment by aouinizied** [comment]
@tanjoreg 
Could you please try to install it using pip and python3.7 just to check that everything is OK.

**Comment by tanjoreg** [comment]
> @tanjoreg
> Could you please try to install it using pip and python3.7 just to check that everything is OK.

**Yes this worked.** I was using anaconda, which had python 3.6. I have upgraded anaconda to 3.7.6 and tried to pip install. It installed 3.2.2

(TF) ME-MacBook-Pro:~$ pip install nfstream
Collecting nfstream
  Downloading nfstream-3.2.2-cp37-cp37m-macosx_10_15_x86_64.whl (446 kB)
     |████████████████████████████████| 446 kB 659 kB/s 
Requirement already satisfied: pyzmq>=18.1.1 in ./anaconda3/envs/TF/lib/python3.7/site-packages (from nfstream) (18.1.1)
Requirement already satisfied: cffi>=1.13.1 in ./anaconda3/envs/TF/lib/python3.7/site-packages (from nfstream) (1.14.0)
Requirement already satisfied: pycparser in ./anaconda3/envs/TF/lib/python3.7/site-packages (from cffi>=1.13.1->nfstream) (2.20)
Installing collected packages: nfstream
Successfully installed nfstream-3.2.2

**Comment by aouinizied** [comment]
Thank you for your feedback. Use python3.7 as it's the version used in our CI for macOS.

**Comment by tanjoreg** [comment]
> Thank you for your feedback. Use python3.7 as it's the version used in our CI for macOS.

**Thanks** for your swift reply & support. **Really appreciate, Zied.**
