### ISSUE TITLE
max_packets feature

### ISSUE THREAD

**Issue by RadionBik** [aouinizied/nfstream#12]
Hello!

It is great to see how the library has matured over these months!

One thing that is possibly missing is setting max packet limit per flow. I have seen in literature many times how guys evaluated performance of classifiers given limited number of packets per flow. As I understand, there is the `active_timeout` parameter, which can not provide guaranties of capturing sufficient statistics, or on contrary, may lead to a delay on flow export even when there are enough stats already.

How do you think, how difficult is to implement a trigger for exporting flows when a predefined packet count has been reached? There might be issues with nDPI, as I saw before, the limit can be reached earlier than a tag is assigned, so a workaround might be just to stop updating flow stats upon the threshold and wait for nDPI. 

Also, is it possible to use the library in nDPI-free mode? let's say we just want to export features online to pre-trained algorithms.

BR,
Radion

**Comment by aouinizied** [comment]
Hi Radion, 

First point is regarding active_timeout, it do not introduce any delay, you can just see it as time based cutter of the flow and it's intended to monitor periodically long life flows.

Regarding the your question, what I understand is that you focus on limited fixed sizes of flows to establish statistics. Indeed, this could be useful for early traffic classification based on only first 10 packets for example.

Such part is partially done but regarding identification engine with NFStreamer options max_tcp_dissections and max_udp_dissections as as documented here: https://nfstream.github.io/docs/api#nfstreamer-the-export-layer

Note also that setting dissect option to false will disable all nDPI code part.

I was thinking about adding an option (let's say sub_flow_size) where if the parameter is set to a value > 0 we compute statistics to this sub flow as part of flow features.

However I see it as an addition to current statistics, I mean that you can set sub_flow and disable statistics or enable both and thus get both early and post-mortem statistics.

Now forcing the export is possible and can be done in your NFPlugin as showed in this example: https://nfstream.github.io/docs/#start-your-ml-powered-streamer
However, you have to deal with the rest of the packets that will create a new flow. 

So I propose more a keep it as sub_flow statistics, user could be eventually predict the output in realtime, however forcing the flow export is not a good idea.

Example a flow with 100 packets and you want to export as soon as you hit 5 packets.
So first 5 packets are OK, you predict and you export.
Second 5 packets -> new flow creation and you predict too and export and so on which will lead to 20 predictions on same flow.

However if we implement it as a sub flow analysis, you can do your prediction once and obtain the all ad flow features.

Regarding the implementation, as showed in the ML example above, it's designed to be used in such scenario such it is not complicated.

Keep me informed if you need some help.
