### ISSUE TITLE
ja3_client and ja3_server are not always exported correctly

### ISSUE THREAD

**Issue by Marcuccio** [aouinizied/nfstream#14]
**Describe the bug**
The ja3 fields are not always exported. 
I double checked the results with [salesforce/ja3](https://github.com/salesforce/ja3). Running the before mentioned tool I manage to retrieve thousands of entries. nfstream with the same pcap doesn't export any ja3_client

**To Reproduce**
1. Go to 'https://mcfp.felk.cvut.cz/publicDatasets/CTU-Malware-Capture-Botnet-243-1/' and dowload the pcap file
2. feed nfstream with the pcap

`df = NFStreamer(source="./2017-04-12_win5.pcap", enable_guess=False).to_pandas()`

3. Aggregate the flows per ja3 and check how many j3a_fields are correctly exported

```
df.groupby(['j3a_client']).agg({
     'bidirectional_duration_ms': ['count']
})
```

4. Install [salesforce/ja3](https://github.com/salesforce/ja3) and run:

`ja3 2017-04-12_win5.pcap`

5. the 2 output are different

**Expected behavior**
The ja3 fields should be equivalent in number and value

**Additional context**
I don't believe this is a bug of nfstream itself. But I am not able to find a explanation for this inconsistency. Can you help me? Is there any good reason for this behaviour?

**Comment by aouinizied** [comment]
@Marcuccio Thanks for the report. I will check and keep you informed.

**Comment by aouinizied** [comment]
@Marcuccio I checked using your pcap file example:
* So, indeed using nfstream, j3a_client is filled with Nans.
* nfstream j3a fingerprinting is based on nDPI library.
* Using nDPI demo app: ndpiReader -q -t -i /home/aouinizied/Documents/2017-04-12_win5.pcap -C 2017-04-12_win5.csv produce a csv with j3ac columns filled with Nans too.
* Based on that, nfstream reports correctly the j3a fingerprint reported by nDPI library.

**Comment by aouinizied** [comment]
So the reason why the output of nDPI is different from the one from j3a lib should be tracked within nDPI. Please report this within nDPI and we will investigate.

**Comment by Marcuccio** [comment]
Luca Deri, manteiner of nDPI, should have fixed the bug in the library: 
https://github.com/ntop/nDPI/issues/906#issuecomment-647487739

Is it possibile to include the fix in nfstream also?

**Comment by aouinizied** [comment]
@Marcuccio Thanks. It will be automatically included in next release.
