### ISSUE TITLE
nfstream installation issue on Raspberry Pi

### ISSUE THREAD

**Issue by geojins** [aouinizied/nfstream#15]
**Newer versions of nfstream not getting installed via pip**
- This issue is occurring on a Raspberry Pi with python 3.7 and pip version 20.1

> root@pimonus065:/home/pi/jins# python3.7 -m pip install nfstream==5.1.2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement nfstream==5.1.2 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 3.1.0)
ERROR: No matching distribution found for nfstream==5.1.2

When I add -vvv option to pip, i get following message( bunch of them for each version) - 
> Skipping link: none of the wheel's tags match: pp36-pypy36_pp73-manylinux1_x86_64: https://files.pythonhosted.org/packages/62/16/fe4f13d7c1a8ed87fcf4632e80afd0d089bf2e8a6d9ab79290973aff6517/nfstream-5.1.2-pp36-pypy36_pp73-manylinux1_x86_64.whl#sha256=a5ed69de3a9901a4a35fed40c09e0ff7f9871577db42258f7fe196d0a13c234b (from https://pypi.org/simple/nfstream/)

When I looked at 3.1.0 verison, pip with -vvv option prints 
>   Found link https://files.pythonhosted.org/packages/17/10/5801bb50ffe3b3e1a73b95a0958e88693bb6ec48c3e9a066df55e1fcb337/nfstream-3.1.0.tar.gz#sha256=85e4d7d16d2dd5b706a591c62a8a8b5da50883dfa23810841b9fe55c3a44ae5e (from https://pypi.org/simple/nfstream/), version: 3.1.0

Since Pi is arm based, does the packages should also include a version for arm architecture? Please suggest if any workarounds possible.

**Comment by aouinizied** [comment]
@geojins Indeed, we do not publish wheels for arm.
Could you try build from source as indicated on the doc (Linux section).
Based on your feedback, We will probably add arm wheels for next release using Travis CI which supports ARM architecture.

**Comment by geojins** [comment]
@aouinizied , I am able to build from source. Importing NFStreamer failed with following error in my script. But I guess this is something to do with my Os/setup.

If you can publish a wheel for arm, I can try to get a different Pi and test. 

> /usr/local/opt/python-3.7.0/lib/python3.7/site-packages/zmq/backend/cython/error.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: zmq_strerror

**Comment by aouinizied** [comment]
This is related to pyzmq on Raspberry PI.
https://github.com/zeromq/pyzmq/issues/1323
Treated here.

**Comment by geojins** [comment]
@aouinizied , thanks. Looks like the behavior is different on diff OS. Would you be able to publish arm wheel in next release? I'll see if I can find couple of OS to verify

**Comment by aouinizied** [comment]
We released a new version with arm wheels (64 bits)
https://travis-ci.org/github/aouinizied/nfstream
However I think the rpi is using 32 bits and I didn't find an easy way to automate wheels publishing using CI for such architecture. So the best option for RPI remains building from source.
