### ISSUE TITLE
Get packets associated per flow

### ISSUE THREAD

**Issue by haripriyaharikumar** [aouinizied/nfstream#16]
How to get the packet (ids) associated with a flow using nfstream?
I would like to dig into the packets associated with each flow.
 For example let's say I would like to get the timestamp associated with the n-th packet in a particular flow. Is it possible with nfstream?

**Comment by aouinizied** [comment]
Yes, this is achievable using NFPlugins.

**Comment by haripriyaharikumar** [comment]
you mean with a user-defined NFPlugin or the already existing one? I cannot find any ids which is of the packets in the flow?

**Comment by haripriyaharikumar** [comment]
Could you please explain how to do it? I am not able to find a solution for this using nfstream.

**Comment by aouinizied** [comment]
here a simple example of extracting timestamp of the fourth packet:

```python
class fouth_packet_of_flow_ts(NFPlugin):        
    def on_update(self, pkt, flow):
        if flow.bidirectional_packets == 4:
            flow.fouth_packet_of_flow_ts = pkt.time

df = NFStreamer(source="pcaps/google_ssl.pcap", plugins=[fouth_packet_of_flow_ts()]).to_pandas()
```

Is this what you want to achieve?

**Comment by haripriyaharikumar** [comment]
Thanks for your reply @aouinizied.
Sorry for the confusion.
Actually I wanted to get the id (indices) of the packets in the original .pcap file associated with a given flow. For example, given NF for the **NFEntry id=3**, what are the packets associated with it from the original .pcap file, let's say **ids_of_packets_ingiven_flow** =[packet_no:7, packet_no:10, packet_no:14]. These indices are the indices of the original .pcap file use to aggregate the flow with id 3.
Later on, I want to make use of these indices to access the timestamp.
--
