### ISSUE TITLE
After Pip install getting error when it is ran in spyder.

### ISSUE THREAD

**Issue by naveed981** [aouinizied/nfstream#17]
Hello I have successfully installed it using pip. It throws me an error when i ran it in my spyder.  I am sharing the error and my code snippet. 
![git1](https://user-images.githubusercontent.com/66297551/83495686-79fd8780-a4d1-11ea-9ada-5f85aee93a75.JPG)
![git2](https://user-images.githubusercontent.com/66297551/83495701-7d910e80-a4d1-11ea-95a4-a7b0c899a215.JPG)

**Comment by aouinizied** [comment]
Windows is not supported yet.
Only MacOS and Linux based systems are supported.

Zied

**Comment by naveed981** [comment]
So now I have installed it on my linux machine. Now i am getting some error like NFStreamer as no attribute "to pandas" you can see in screenshots.
![Selection_006](https://user-images.githubusercontent.com/66297551/83503823-1e38fb80-a4dd-11ea-8d02-be2d68423ec3.png)
![Selection_007](https://user-images.githubusercontent.com/66297551/83503824-1f6a2880-a4dd-11ea-95aa-934d10eb8555.png)

**Comment by aouinizied** [comment]
which version of Python are you using and which of nfstream did you download?

**Comment by naveed981** [comment]
I am using python 3.5.2. I have installed it using pip command. pip install nfsteam

**Comment by aouinizied** [comment]
As stated in the documentation, nfstream is supported for Python version >=3.6.
So, please update to 3.6, 3.7, or 3,8 and rerun your installation to get the last version of nfstream.
