### ISSUE TITLE
Feature request: application layer data per flow

### ISSUE THREAD

**Issue by sunny-r** [aouinizied/nfstream#18]
Hi,
Would it be possible to add a few methods to the NFEntry object that would give access to all of the application layer data, per direction of a flow? 
For example, if a flow contained a HTTP Request and a HTTP Response, it would be cool to run something like `flow.src2dst_application_layer.bytes()` to get the entire request as a byte array.
And conversely, `flow.dst2src_application_layer.bytes()` for the response.
Cheers!

**Comment by aouinizied** [comment]
Maybe we could add some additional metadata extraction with response and request parsing results.
Example: flow.http_user_agent, flow.http_content_type, etc.
What do you think about it?

**Comment by sunny-r** [comment]
That would work well for HTTP, but I was mostly using HTTP as an example - I care about a range of protocols including HTTP, DNS, TLS (certificates, and handshakes), SSH, etc. 
I might want to regex scan the payloads for certain text, or extract fields of interest for later analysis.
Wireshark (or tshark) do this well, but the dissection only works against specified ports (so is no good if SSH traffic is not on port 22, for example) 
I understand that this could become expensive on some networks, but for my home LAN, volumes should be manageable.
I considered using NFPlugin, and had a look in the source code, but my python isn't strong enough to see where I could append the layer 7 bytes to a variable in the flow object.

**Comment by sunny-r** [comment]
Hi, I think I've made progress using NFPlugin:

    class myplugin(NFPlugin):
        direction0bytes = b''
        direction1bytes = b''

        pkts=[] # temporary array to hold all pkts in flow; just for testing

        def handle_pkt(self,pkt):
            self.pkts.append(pkt)
            d = pkt.direction
            if pkt.payload_size == 0:
                return
            else:
                if d == 0:
                    self.direction0bytes += pkt.ip_packet[-pkt.payload_size:]
                else:
                    self.direction1bytes += pkt.ip_packet[-pkt.payload_size:]

        def on_init(self, pkt):
            self.handle_pkt(pkt)

        def on_update(self, pkt, entry):
            self.handle_pkt(pkt)

        def on_expire(self,entry):
            entry.d0bytes = self.direction0bytes
            entry.d1bytes = self.direction1bytes
            entry.pkts = self.pkts

`direction0bytes` and `direction1bytes` hold the application layer data in each direction for a given flow.

For test data, I'm using a single bidirectional flow that contains one HTTP Request, and the corresponding HTTP Response; it comprises 11 packets. 
I'm comparing the 11 `NFPacket` objects to what Wireshark presents.

All of the `NFPacket.raw_size` matches the Frame size seen in Wireshark - that's good.

But I wonder if NFPacket sometimes has an incorrect payload_size. For the first packets in the flow (src2dst (SYN) and the dst2src (SYN-ACK)), Wireshark shows lengths of 0, but the equivalent NFPackets have payload_size of 20, and 8, respectively. Why could this be happening? There shouldn't be a discrepancy in payload lengths between nfstream and Wireshark?

I notice that the NFPacket object has `ip_packet` property - can we get a `payload` property for each NFPacket, whose length matches the NFPacket `payload_size`? 
If that's in the NFPacket object, and the payload and payload length extraction is accurate, then I can use NFPlugin to solve this 'application layer data per flow' problem.

**Comment by aouinizied** [comment]
Thanks for your feedback.
For payload length difference, it's a bug. (a stupid typo)
https://github.com/aouinizied/nfstream/blob/318251a1fadfbd3c246c74689da69198e17cde51/nfstream/observer.py#L180
I will fix it by replacing transport_size by payload_size. Thanks for the shoot. I doubled checked other attributes and everything seems OK. Next release will patch it.

Regarding, the feature you are working on. Did you notice that there is already exported metadata in client_info and server_info (DNS server name, it's server names, etc.) that are populated using nDPI NFPlugin?

I think what you try to extract is already extracted using nDPI plugin and needs only to be copied as others in NFEntry.

So please check the following structure:
https://github.com/aouinizied/nfstream/blob/318251a1fadfbd3c246c74689da69198e17cde51/nfstream/ndpi.py#L995
Everything in it is already handled using nfstream and we can add more attributes to NFEntry by simple copy from nDPI plugin. (HTTP method, TLS version, content type, user agent, etc)
If there is something missing, I will add it to nDPI library. (I prefer to keep parsing functions in C for performances reasons)

What do you think about it?

**Comment by sunny-r** [comment]
Hi, thanks for getting that fix in for next release.
I hear you on preferring the nDPI library for performance reasons, but i can only see simple strings extracted into the `client_info` and `server_info` fields, and there's not enough data.

For example, for a pair of DNS packets (one with the DNS question, and the other with DNS response), only the question is captured into `server_info`. None of the CNAME data is captured.

As another example, for HTTP, the `client_info` is empty, and only the Host is in `server_info`.

It would be good to have a python dictionary in the flow object containing the NDPI data extracted, and more data in there. 

TLS certificates (with things like certificate issuer) would also be good to have, and the ALPN extension, and so on.

How can I extend the NDPI library to extract my field-of-interest.

Thanks!

**Comment by sunny-r** [comment]
Bump! Can you give me any pointers on how I can use NDPI to extract more payload information?

**Comment by aouinizied** [comment]
@sunny-r It depends on the use case. for TLS and HTTP I think everything is already extracted in the ndpi_flow_struct. If you have metadata that do not appear there then you need to create a new dissector (nDPI doc explain how) or modify TLS or HTTP existing ones.

**Comment by sunny-r** [comment]
Alright, I'll have a deeper look at the NDPI docs. In any case, I'll close this thread as I can use NFPlugin to capture the entire payload if I wanted to (though NDPI is faster). Cheers.

**Comment by aouinizied** [comment]
@sunny-r I will reopen it when I will add more metadata extraction to keep you informed. (Probably the next release)
