### ISSUE TITLE
Less number of rows ( instances ) generated in csv file

### ISSUE THREAD

**Issue by naveed981** [aouinizied/nfstream#19]
I was using the nfstream data.to_csv function on one of my pcap files. But the instances I am getting is very much less ( rows in csv file).
Is there any way to customize it ?

**Comment by aouinizied** [comment]
@naveed981 additional details such as code example, python version, pcap files will be useful in order to reproduce and answer your question. Thanks.

**Comment by naveed981** [comment]
Python 3.6.9 I am using 
I have tried the both ways converted to pandas data frame then convert to csv and with out converting directly as shown in this code.
![git11](https://user-images.githubusercontent.com/66297551/85829712-ac369800-b7a4-11ea-89fc-368eb461e62a.JPG)
![git22](https://user-images.githubusercontent.com/66297551/85829721-b193e280-b7a4-11ea-99c5-130709349109.JPG)

**Comment by aouinizied** [comment]
And what is the issue? what do you mean by less?

**Comment by naveed981** [comment]
@aouinizied by less number I mean the number of rows I am getting in the CSV file. As I am training ML classifier. I am getting only 1600 rows.

**Comment by aouinizied** [comment]
And what is the expected number? Maybe there is only 1600 flows in your pcap. Which reference are you using?
