### ISSUE TITLE
Some pcap files cannot be processed

### ISSUE THREAD

**Issue by jsrojas** [aouinizied/nfstream#3]
Hi again

I was just testing nfstream following the documentation. It works great but for some reason with some pcap files I get the following error:

Traceback (most recent call last):
  File "/home/jsrojas/Juan/Unicauca/Doctorado/PhD Internship/Python Projects/nfstream-test/nfstream-test.py", line 11, in <module>
    for flow in capture_streamer:  # or for flow in my_live_streamer
  File "/usr/local/lib/python3.6/dist-packages/nfstream/streamer.py", line 266, in __iter__
    for pkt_info in pkt_info_gen:
  File "/usr/local/lib/python3.6/dist-packages/nfstream/observer.py", line 94, in __iter__
    packet_information = process_packet(timestamp, packet)
  File "/usr/local/lib/python3.6/dist-packages/nfstream/observer.py", line 54, in process_packet
    return PacketInformation(ts=int(ts*1000), size=len(buf), content=bytes(ip),
  File "/home/jsrojas/Juan/Unicauca/Doctorado/Python Projects/venv/lib/python3.6/site-packages/dpkt/ip.py", line 111, in __bytes__
    return self.pack_hdr() + bytes(self.opts) + bytes(self.data)
  File "/home/jsrojas/Juan/Unicauca/Doctorado/Python Projects/venv/lib/python3.6/site-packages/dpkt/gre.py", line 118, in __bytes__
    opt_s = struct.pack(b''.join(fmts), *vals)
TypeError: sequence item 0: expected a bytes-like object, str found

This is the code I'm using, following the docs:
```
from nfstream.streamer import Streamer
import pandas as pd

capture_streamer = Streamer(source="/home/jsrojas/Juan/Unicauca/Doctorado/PhD Internship/Task 1 - Comparison of Flow Monitoring tools/TestFile.pcap",
                               capacity=128000,
                               active_timeout=120,
                               inactive_timeout=60)

df_flows = pd.DataFrame(columns=['src_ip', 'src_port', 'dst_ip', 'dst_port', 'Forward_pkts', 'Backward_pkts', 'Forward bytes', 'Backward bytes', 'start_time', 'end_time', 'category_name','application_name'])

for flow in capture_streamer:  # or for flow in my_live_streamer
    #print(flow.ip_src)  # print, append to pandas Dataframe or whatever you want :)!
    df_flows = df_flows.append({'src_ip': flow.ip_src, 'src_port': flow.src_port, 'dst_ip': flow.ip_dst,
                                'dst_port': flow.dst_port, 'Forward_pkts': flow.src_to_dst_pkts, 'Backward_pkts': flow.dst_to_src_pkts,
                                'start_time': flow.start_time, 'end_time':flow.end_time, 'category_name': flow.category_name, 'application_name': flow.application_name}, ignore_index=True)

    df_flows.to_csv (r'/home/jsrojas/Juan/Unicauca/Doctorado/nDPI-flows-dataframe.csv', index = None, header=True)
```
Am I doing something wrong? or are there some kind of restriction regarding the pcap files?

Thanks in advance

**Comment by aouinizied** [comment]
Hi, 
It's due to dpkt parsing library.
Have a look at tests repository, there is a future repo that points to cases like you have.
I don't known if we need to open an issue on dpkt. Or we need to investigate on how to parse it correctly. 
Try to parse your pcap with dpkt, can you obtain IP level information?

**Comment by jsrojas** [comment]
Hi,
I will try check on what is happening with dpkt and get back to you asap.
Meanwhile can you share with me any documentation or understanding that you have about the python bindings please? I do understand the purpose of calling C functions into python code but I have not been able to know how the nDPI process is on the inside (which functions to call, which variables are important?)

So if you can share something of this with me maybe I can start contributing to nfstream because it does precisely what I want to do. Thanks in advance

BR

**Comment by aouinizied** [comment]
Look how we implemented NDPIClassifier: https://github.com/aouinizied/nfstream/blob/master/nfstream/classifier.py

I added some documentation here:
https://nfstream.readthedocs.io/en/latest/tutorials.html#create-your-own-classifier

Mainly for nDPI you will use process_packet or give_up

BR

**Comment by aouinizied** [comment]
GRE now is parsed correctly. We added a test file for this use case. You can retry with same pcap file. It should work.

**Comment by jsrojas** [comment]
Hi.

Thank you very much. It is in fact reading the file now, but I have one small observation: I think that something is missing from the flow class because when I try to print the application_name or category_name it tells me that none of the attributes exist, like this:

```
from nfstream.streamer import Streamer

capture_streamer = Streamer(source="/home/jsrojas/Juan/Unicauca/Doctorado/PhD Internship/Task 1 - Comparison of Flow Monitoring tools/SSL Instagram.pcap",
                               capacity=128000,
                               active_timeout=120,
                               inactive_timeout=60)

for flow in capture_streamer:
    print(flow.application_name)
    print(flow.category_name)
```
I get this:

Traceback (most recent call last):
  File "/home/jsrojas/Juan/Unicauca/Doctorado/PhD Internship/Python Projects/nfstream-test/nfstream-test.py", line 12, in <module>
    print(flow.application_name)  # print, append to pandas Dataframe or whatever you want :)!
AttributeError: 'Flow' object has no attribute 'application_name'

I am able to see it when I print the metrics attributes like this:

```
from nfstream.streamer import Streamer

capture_streamer = Streamer(source="/home/jsrojas/Juan/Unicauca/Doctorado/PhD Internship/Task 1 - Comparison of Flow Monitoring tools/SSL Instagram.pcap",
                               capacity=128000,
                               active_timeout=120,
                               inactive_timeout=60)
for flow in capture_streamer:
    print(flow.metrics)
```
It prints this:

{'application_name': 'TLS.Instagram', 'category_name': 'SocialNetwork'}
{'application_name': 'TLS.Instagram', 'category_name': 'SocialNetwork'}
{'application_name': 'TLS.Instagram', 'category_name': 'SocialNetwork'}
{'application_name': 'TLS.Instagram', 'category_name': 'SocialNetwork'}

So I think something is missing in the Flow class from the streamer.py file

BR

**Comment by aouinizied** [comment]
Flow class will contain only core metrics strating from next release. I moved ndpi to metrics, you can also find it in classifiers dict under flow. We need to update the doc when released. And change the major version as API broken.

**Comment by jsrojas** [comment]
Yeah I got later through the flow.classifier dictionary like this:

`print(flow.classifiers['ndpi']['application_name'])`

Thanks a lot.

BR
