### ISSUE TITLE
serialization error

### ISSUE THREAD

**Issue by RadionBik** [aouinizied/nfstream#4]
Hello!

Thank you for the improvements you have made!

At this point, I encounter error related with serialization error when `Flow.__str__` method is called for flows with non-serializable metrics  (e.g. custom objects). I suggest replacing json.dumps with str() method to allow printing in such cases.

**Comment by aouinizied** [comment]
Can you test with master (from source) and confirm it's solved?
Note that API compatibility is broken as we will release 1.0 soon.
