### ISSUE TITLE
improvement: JA3

### ISSUE THREAD

**Issue by RadionBik** [aouinizied/nfstream#5]
Hello!

I was wondered how difficult would be to write bindings for extracting JA3 fingerprints (https://github.com/salesforce/ja3), that are already implemented in nDPI. I would be beneficial to use it is as a categorical flow feature for ML classification, for example. Of course, one can calculate on their own, but if already exists in nDPI, why not to use it?

**Comment by aouinizied** [comment]
Hi Radion,

I made major changes in nfstream architecture. 
The aim is to drastically improve performances (multithreading and pypy jit support).
So now nfstream X2 faster using Python and X10 faster using PyPY.
I also added your request (j3a fingerprints) and fixed ndpi application name (now the output is the same as nDPI).
Moreover, major API change as now both metric and models are considered as plugins.
Have a look at docs for more informations.[https://nfstream.readthedocs.io/en/latest/?badge=latest]
Is it possible to have your feedback running nfstream from latest source?
nfstream 2.0 will be released soon.

Regards,
Zied
