### ISSUE TITLE
What is nfstream considering when calculating the size of packets?

### ISSUE THREAD

**Issue by jsrojas** [aouinizied/nfstream#6]
Hello

Just one quick question: When nfstream calculates attributes like  src2dst_bytes or dst2src_bytes what is being considered in the calculation i.e., is it the size of the IP header only or does it have a mixture of the different headers that are created during the encapsulation?

Thanks in advance for the help.

Best regards.

**Comment by aouinizied** [comment]
Hi Juan,
For src2dst_bytes or dst2src_bytes, the computation is done using the actual lentgh of the packet.
If you want to compute only ip size you can perform it by adding a plugin that will just cumulate len(obs.raw) in place if obs.length (raw field in NFPacket contains the packet starting from IP layer).
BR,
Zied

**Comment by jsrojas** [comment]
Hello again Dr. Aouini

Thank you very much for your answer. I was comparing some measurements done by nfstream with other tools and there was this minor difference in the packet sizes because most of the tools consider the payload size only. I imagined the reason was going to be something similar to what you answer but I wanted to be sure of it. 

BR

**Comment by aouinizied** [comment]
You're welcome! I keep the issue open until I update the documentation according to that.
Zied
