### ISSUE TITLE
Active Timeout

### ISSUE THREAD

**Issue by matthbr** [aouinizied/nfstream#8]
Hello

Just a quick question. Do I understand it correctly that the active timeout is chopping long flows up into segments of maximal length of the active timeout? And if this is the case why is this done and would it be possible to turn this off?

Thanks in advance for any help.
Best Regards

**Comment by aouinizied** [comment]
Hi @matthbr,

Yes, your understanding is correct.
Why it is done? it's a standard flow expiration trigger in flow monitoring architecture and is used mainly for long life flow live monitoring use case.

Example:
Let's say that you have a stream (from camera device) that continiously send packets on a unique UDP flow.
If you do not set an active-timeout, you will never see that flow. Active timeout in this case is usefull to have periodic status of that flow.
We can turn it off if we set it with a very large value (1 year in seconds) or simply infinite.

BR,

**Comment by matthbr** [comment]
Hello Dr. Aouini,
Thanks for the quick reply.

In your example, the active timeout would definitively make sense. In my case I have prerecorded PCAPs in which case I prefer that the long flows are not cut apart.

This means, it would be possible to set the active timeout to a value of several hours?
Based on your documentation I assumed the allowed range for this parameter is only from 15 seconds to 5 minutes (page 6 under Entry expiration)...
If this is not the case, it might need some clarification in the documentation. Especially since on in the description of the NFStreamer object (chapter 3.1) there is no range stated which lead to my assumption on the limitation to the range of 15 seconds to 5 minutes.

Best Regards

**Comment by aouinizied** [comment]
Hi @matthbr ,

That's true, the documentation range was uncorrect. I removed it from doc (Thanks! :smile:  ).
Active-timeout take any integer as value (if it's negative it will be set to zero).
Consequently, you can set to very large value (in seconds) if you want to turn it off.

BR,
Zied
