### ISSUE TITLE
Pcap to dataframe is taking very long time

### ISSUE THREAD

**Issue by tanjoreg** [aouinizied/nfstream#9]
Hi,
Thanks for this fantastic library. I was looking for such a library since long. I am experimenting with this nfstream library but stuck.
I am using the "skype.pcap" available in nfstream/tests/pcap/   folder which is 700kb. I used the following code mentioned in the documentation.

from nfstream import NFStreamer
df = NFStreamer(source="skype.pcap").to_pandas()

Its been more than an hour and this code is still executing in my jupyter. Does it really take time or am I missing something here? Kindly help.

**Comment by tanjoreg** [comment]
some logs....
There is no error yet..the code is still running...with following log

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/guru/nfstream/nfstream/cache.py", line 136, in consume
    entry = self._roots[obs.root_idx][obs.nfhash].update(obs,
  File "/Users/guru/nfstream/nfstream/cache.py", line 35, in __getitem__
    return super().__getitem__(key)
KeyError: (17, 0, 3232235777, 3232235810, 53, 49163)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ME/opt/miniconda3/envs/tf/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/ME/opt/miniconda3/envs/tf/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ME/nfstream/nfstream/cache.py", line 172, in run
    self.consume(observable)
  File "/Users/ME/nfstream/nfstream/cache.py", line 157, in consume
    self.idx_generator)
  File "/Users/ME/nfstream/nfstream/entry.py", line 27, in __init__
    setattr(self, plugin.name, plugin.on_init(obs))
  File "/Users/ME/nfstream/nfstream/plugin.py", line 238, in on_init
    p = self.user_data.ndpi_detection_process_packet(f, obs.ip_packet, obs.ip_size, obs.time, s, d)
  File "/Users/ME/nfstream/nfstream/ndpi.py", line 1388, in ndpi_detection_process_packet
    return self._ndpi.ndpi_detection_process_packet(self._mod, flow, packet, packetlen, current_tick, src, dst)
OverflowError: can't convert negative number to unsigned

**Comment by aouinizied** [comment]
Hi @tanjoreg ,

Thanks for reporting this.

"skype.pcap" is used for all our tests on MacOS and ubuntu.
You can play with skype using the live notebook. Just replace instagram.pcap by skype.pcap

https://mybinder.org/v2/gh/aouinizied/nfstream-tutorials/master?filepath=demo_notebook.ipynb

On which platform are you encountering such issue?
Which version of nfstream?
Did you install it using pip or by cloning it?

Best regards,
Zied

**Comment by tanjoreg** [comment]
Hi Zied, thanks for swift response.
I am on MacOS and cloned it as pip was installing an older version, which didn’t had support for to_pandas().

**Comment by aouinizied** [comment]
which macOS version?

**Comment by tanjoreg** [comment]
MacOS Mojave 10.14.5

**Comment by aouinizied** [comment]
and which nfstream version pip is installing?

**Comment by tanjoreg** [comment]
pip is installing 3.1.2 and I saw that nfstream is updated and to_pandas() is available in 3.2.2

(tf) ME:~ guru$ pip install nfstream
Collecting nfstream
  Using cached https://files.pythonhosted.org/packages/9c/ca/7ae7e66e26e2827baa4c045e8a849b089ddc1735209e3d49c61fe541ec98/nfstream-3.1.2-cp36-cp36m-macosx_10_13_x86_64.whl
Requirement already satisfied: cffi>=1.13.1 in ./opt/miniconda3/envs/tf/lib/python3.6/site-packages (from nfstream) (1.14.0)
Requirement already satisfied: pyzmq>=18.1.1 in ./opt/miniconda3/envs/tf/lib/python3.6/site-packages (from nfstream) (19.0.0)
Requirement already satisfied: pycparser in ./opt/miniconda3/envs/tf/lib/python3.6/site-packages (from cffi>=1.13.1->nfstream) (2.20)
Installing collected packages: nfstream
Successfully installed nfstream-3.1.2

**Comment by aouinizied** [comment]
which is normal as we build wheels only for macos 10.15 and latest.
I will build and publish wheels for macos 10.14 and you will be able to install it using pip.

which instructions did you use to install it from source?

**Comment by tanjoreg** [comment]
Thanks Zied. Appreciate your help. I just followed the documentation and used the following instructions.

    brew install autoconf automake libtool pkg-config
    git clone https://github.com/aouinizied/nfstream.git
    cd nfstream
    python3 -m pip install -r requirements.txt
    python3 setup.py install

**Comment by aouinizied** [comment]
Could you try doing the following? (after removing nfstream repo using rm -rf nfstream)

brew install autoconf automake libtool pkg-config
git clone https://github.com/aouinizied/nfstream.git
cd nfstream
python -m pip install --upgrade pip
python3 -m pip install wheel twine setuptools codecov
python3 -m pip install -r requirements.txt
python3 setup.py bdist_wheel

**Comment by aouinizied** [comment]
and also for pip installation try the following and see if you get the same version.

pip install --no-cache-dir --upgrade nfstream

**Comment by tanjoreg** [comment]
> Could you try doing the following? (after removing nfstream repo using rm -rf nfstream)
> 
> brew install autoconf automake libtool pkg-config
> git clone https://github.com/aouinizied/nfstream.git
> cd nfstream
> python -m pip install --upgrade pip
> python3 -m pip install wheel twine setuptools codecov
> python3 -m pip install -r requirements.txt
> python3 setup.py bdist_wheel

This worked like charm....now it works....
I just tried with instagram.pcap and it is done in no time. KUDOS to your help.

**Comment by tanjoreg** [comment]
> and also for pip installation try the following and see if you get the same version.
> 
> pip install --no-cache-dir --upgrade nfstream

Yes it is same version 3.1.2

tf) ME:~ ABC$ pip install --no-cache-dir --upgrade nfstream
Collecting nfstream
  Downloading nfstream-3.1.2-cp36-cp36m-macosx_10_13_x86_64.whl (320 kB)
     |████████████████████████████████| 320 kB 398 kB/s 
Requirement already satisfied, skipping upgrade: pyzmq>=18.1.1 in ./opt/miniconda3/envs/tf/lib/python3.6/site-packages (from nfstream) (19.0.0)
Requirement already satisfied, skipping upgrade: cffi>=1.13.1 in ./opt/miniconda3/envs/tf/lib/python3.6/site-packages (from nfstream) (1.14.0)
Requirement already satisfied, skipping upgrade: pycparser in ./opt/miniconda3/envs/tf/lib/python3.6/site-packages (from cffi>=1.13.1->nfstream) (2.20)
Installing collected packages: nfstream
**Successfully installed nfstream-3.1.2**

**Comment by aouinizied** [comment]
Happy to hear that!
I will update documentation with correct instructions list.
Also, i will try to enlarge the platform list for wheels including Mojave.

Zied

**Comment by tanjoreg** [comment]
> Happy to hear that!
> I will update documentation with correct instructions list.
> Also, i will try to enlarge the platform list for wheels including Mojave.
> 
> Zied

But pip still installs 3.1.2 Hope you have noted that.
